services:
  - type: web
    name: geotube
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GOOGLE_YOUTUBE_API_KEY
        value: ""
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ""
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ""
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ""
